### ISSUE TITLE
Unable to edit blogs

### ISSUE THREAD

**Issue by tranpl** [oqtane/oqtane.blogs#44]
Microsoft.JSInterop.JSException: Cannot read properties of null (reading '__quill')
TypeError: Cannot read properties of null (reading '__quill')
    at Object.getQuillHTML (https://localhost/js/quill-interop.js:30:30)
    at https://localhost/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost/_framework/blazor.web.js:1:3201)
    at gn._invokeClientMethod (https://localhost/_framework/blazor.web.js:1:62841)
    at gn._processIncomingData (https://localhost/_framework/blazor.web.js:1:60316)
    at connection.onreceive (https://localhost/_framework/blazor.web.js:1:53957)
    at i.onmessage (https://localhost/_framework/blazor.web.js:1:82102)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Oqtane.Modules.Controls.RichTextEditor.OnAfterRenderAsync(Boolean firstRender) in C:\Source\Projects\oqtane.framework\Oqtane.Client\Modules\Controls\RichTextEditor.razor:line 192
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Oqtane Version 5.1.0
Blog Module Version 5.0.3

**Comment by vnetonline** [comment]
I am also getting the same problem

**Comment by sbwalker** [comment]
@vnetonline are you getting the error from the code in this repo… or from installing the package in the Marketplace?

**Comment by vnetonline** [comment]
From installing it from market place

**Comment by vnetonline** [comment]
I just foredthe repo and I get the same error when trying to edit an existing blog

**Comment by tranpl** [comment]
the blogs module was downloaded from the marketplace, oqtane from github compiled @sbwalker

**Comment by sbwalker** [comment]
Is it possible it could have been resolved by this recent PR - https://github.com/oqtane/oqtane.framework/pull/4111 (Oqtane Framework dev branch)

**Comment by sbwalker** [comment]
I am not able to reproduce this problem using the latest code in the dev branch of the Oqtane Framework

**Comment by vnetonline** [comment]
I am still getting the issue i have run the latest changes from the Dev branch and have just updated the SDK to 8.0.4 on my local copy of the blog still have the same issue 

Adding content is fine 
Unable to edit the content once entered,

I have noticed that the OnInitializedAsync is hit twice and on the second run, the error occurs 

![screencast_blog_edit_errorerror](https://github.com/oqtane/oqtane.blogs/assets/15242923/4fcf03a8-6d8e-4c17-a334-d8b16c4e5036)

**Comment by sbwalker** [comment]
@tranpl @vnetonline I am able to reproduce the problem now... I will investigate further today. Its very strange, as I am using the Blog module on https://www.oqtane.org (and other sites) without any issues.

**Comment by sbwalker** [comment]
@tranpl @vnetonline this PR https://github.com/oqtane/oqtane.framework/pull/4126 resolves the issue in the RichTextEditor. The problem was basically a race condition due to JS Interop. The JS Interop call to CreateEditor on firstRender can sometimes take time (depending on the environment) which means that OnAfterRenderAsync could be called a second time with firstRender = false BEFORE the first OnAfterRenderAsync call completed. This could result in the component trying to access a method on the RichTextEditor before it actually exists. The resolution is to explicitly control the flow within the component by tracking whether the firstRender event completed or not.

**Comment by vnetonline** [comment]
I can confirm that PR https://github.com/oqtane/oqtane.framework/pull/4126 resolves the issue in the RichTextEditor and now I am able to edit the blogs

**Comment by tranpl** [comment]
thank you @sbwalker
